{
    'name': "Elixer Event Management ",
    'category': 'Event Management',
    'website': 'www.elixerevent.com',
    'summary': "Event Management",
    'Sequence': 1,
    'depends': ['mail'],
    'data': [
        'security\management.xml',
        'security\ir.model.access.csv',
        'data\email_template.xml',
        'data\employee_data.xml',
        'data\cus.xml',
        'views\customer.xml',
        'views\cus_address.xml',
        'views\employee.xml',
        'views\event.xml',
        'views\expense.xml',
        'views\invoice.xml',
        'views\order.xml',
        'views\product.xml',
        'views\suplier.xml',
        'views\event_task.xml',
        'views\management.xml',

    ],
    'version': '1.0',
    'installable': True,
    'license': 'LGPL-3',
}
